#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap


if [ -f "Cargo.toml" ]; then
    (cargo build)
    echo "==> App is now ready to go! do 'cargo run' to see output."
fi
